### ISSUE TITLE
Cookie Clicker not loading with this extension active

### ISSUE THREAD

**Issue by JazzyScuffs** [builtinnya/UncannyCookieClicker#12]
Cookie Clicker does not load while this extension is active. This is true for Chrome and Brave and on Live and Beta versions of CC. When I look in the console it gives me the following error:

Uncaught Error: Game.Init is undefined: This extension may not support this version of Cookie Clicker.
page.js:10

Is this still being worked on or should we look for different auto-clickers?

**Comment by builtinnya** [comment]
Thank you for letting me know the problem.
I've submitted the fixed version of UncannyClicker (v0.6.0) for review.

**Comment by builtinnya** [comment]
The fixed version (v0.6.0) has been published.

**Comment by HansMeiser234** [comment]
It's running again.
Thank you for fixing.
