### ISSUE TITLE
Bot doesn't auto-click golden cookies

### ISSUE THREAD

**Issue by Maxplasma** [builtinnya/UncannyCookieClicker#6]
Just something I've noticed. No matter what speed the game is on, Golden Cookies aren't being auto-hit.

**Comment by Maxplasma** [comment]
![61d69e0af479566e4c725e0f5b13cf66](https://cloud.githubusercontent.com/assets/6677874/17088341/da20427e-51ce-11e6-87f8-9ff9ab0cf6e6.jpg)

**Comment by builtinnya** [comment]
@Maxplasma 
Thanks!
Cookie Clicker has just updated its golden cookie system and the issue has existed since beta (#4).
Currently, I don't have enough time to update the extension.
Please be patient, and I always welcome PRs!

**Comment by Maxplasma** [comment]
@builtinnya Well, that kinda sucks to hear, but it's great to know that you're aware of the issue. Cheers!
