### ISSUE TITLE
Compatibility with www.weedclicker.net ?

### ISSUE THREAD

**Issue by BobMaster1982** [builtinnya/UncannyCookieClicker#8]
Hello All,

For the past few days, I have been trying to get this extension to work for http://www.weedclicker.net

This is in essence the exact same game, the only difference is the URL and some "building" names.

When reloading chrome, I get the below error message in the chrome extensions menu, but that isn't telling me much.
![uncanny clicker tool error](https://user-images.githubusercontent.com/45458126/49224490-da45d180-f3e1-11e8-9f68-5c0019b903ac.PNG)
This is simply a line in the pagemessaging.js file, I'm not even sure if this is a real error.

After making the changes, it is still working on http://orteil.dashnet.org/cookieclicker/, so the changes did not break the extension even with the error being shown.

I am very confused as to what is preventing it from working.

Any help would be very much appreciated.

Thanks in advance,
Bart

**Comment by builtinnya** [comment]
Hi, Bart.

If my memory serves me correctly, it uses [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to enable communication between the scripts embedded in the CookieClicker page and the extension.
The intention of  that part of codes is clear. It throws an error if a received message is malformed for UncannyCookieClicker.
The problem is that it assumes that all messages are sent for UncannyCookieClicker and no other systems use `window.postMessage()`.
The code may have to be replaced like the following:

```javascript
if (event.origin !== '<origin url>')
    return;

// Now, we are sure that the message has been sent from the intended origin.

if (!request || !request.cmd || !_.isString(request.cmd))
      return; // Just ignore if the message is malformed
```

**Comment by BobMaster1982** [comment]
Hello,

Thank you for the quick response.

I think I am doing something wrong or forgetting something, I added the following line before the 'request' line:
if (event.origin !== 'http://www.weedclicker.net')
		return;
Replaced the 'throw' line with a: return; 

I did find and change/replace the same lines in messaging.js and pagemessagingproxy.js.

Sadly it is still not working.

When clicking on the icon, I simply get the default chrome extension menu where I can remove it, hide it, etc.

My knowledge of scripting is very basic, but usually editing an existing script does not give me so many problems.

Your help is highly appreciated !

**Comment by builtinnya** [comment]
First of all, UncannyCookieClicker was built for CookieClicker, so there's no guarantee that it also works for WeedClicker however it looks like the same.
Changing CookieClicker URLs in `src/js/modules/config.js` and `src/manifest.json` to WeedClicker's URL can make the extension UI appear, but I doubt that it works as-is.
If you truly want it to work for WeedClicker, this is the time for learning how to build (fix) Chrome extensions!

**Comment by BobMaster1982** [comment]
Hey,

It might be a good idea to start from scratch indeed.

I was just hoping to save some time as this is 100% the same idle game with only a few name changes.

Do you have any resources you can suggest for learning this ?

Thanks again for your time.

Greetings,
Bart

**Comment by builtinnya** [comment]
To learn how to build a Chrome extension, the best resource would be the official document.
[What are extensions? - Google Chrome](https://developer.chrome.com/extensions)

You also have to learn the WeedClicker's source code itself. [Chome Developer Tools](https://developers.google.com/web/tools/chrome-devtools/) is the best tool for learning how the game works. To learn JavaScript, pick whatever works for you from [JavaScript.com | Resources](https://www.javascript.com/resources).
